In [ ]:
# Phase 1 — EDA: Data Loading & Structure Overview

import pandas as pd

df_raw = pd.read_csv("../data/raw/raw_combined_abstracts.csv")
df_raw.head()

                                                text  label
0  كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...      0
1  يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...      0
2  شكلت تلك الجهود والمساعي الرائدة التي قام بها ...      0
3  يقوم المقال على اشكالية الضرائب الغير شرعية في...      0
4  تتفق المصادر التاريخية المتوفرة حول موضوع تطور...      0

In [ ]:
#2) Basic Structure
print("Shape:", df_raw.shape)
df_raw.info()
df_raw.describe(include='all')

Shape: (41940, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41940 entries, 0 to 41939
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    41940 non-null  object
 1   label   41940 non-null  int64
dtypes: int64(1), object(1)
memory usage: 655.4+ KB

                                                     text         label
count                                               41940  41940.000000
unique                                              36525           NaN
top     تعتمد الأمم عبر مر الأزمنة والعصور على لغات تع...           NaN
freq                                                    4           NaN
mean                                                  NaN      0.800000
std                                                   NaN      0.400005
min                                                   NaN      0.000000
25%                                                   NaN      1.000000
50%                                                   NaN      1.000000
75%                                                   NaN      1.000000
max                                                   NaN      1.000000

In [ ]:
#3) Missing Values
df_raw.isnull().sum()

text     0
label    0
dtype: int64

In [ ]:
#4) Duplicates
df_raw.duplicated().sum()

np.int64(5399)

In [ ]:
#5) Distribution of label (Human vs AI)
df_raw["label"].value_counts()
df_raw["label"].value_counts(normalize=True) * 100

label
1    80.0
0    20.0
Name: proportion, dtype: float64

In [ ]:
#5) Distribution of label (Human vs AI)
df_raw[df_raw["label"] == 0].sample(3)   
df_raw[df_raw["label"] == 1].sample(3)

                                                    text  label
32011  يتناول هذا البحث أهمية القياس التربوي والتقويم...      1
23161  يُقدم هذا البحث دراسة أثريّة لقرية أقمون، إحدى...      1
33267  تتناول هذه الدراسة تأثير التجسس الإلكتروني على...      1